# Tested on Armbian Buster 5.93 with custom kernel
# ansible-playbook -k -i 192.168.0.111, playbook.yml
---
- hosts: all
  user: root
  vars_prompt:
    - name: icecast_password
      prompt: "Define Icecast password"
  tasks:
  - name: Configure hardware
    block:
      - copy:
          content: 'blacklist xradio_wlan'
          dest: /etc/modprobe.d/blacklist-xradio.conf
      - replace:
          path: /boot/armbianEnv.txt
          regexp: ^(overlays=(?:(?!cir).)*)$
          replace: \1 cir
  - name: Configure time sync
    block:
      - apt:
          name: ntp
          state: absent
          purge: yes
      - service:
          name: systemd-timesyncd
          state: started
  - name: Add Mopidy repo
    block:
      - apt_key:
          url: https://apt.mopidy.com/mopidy.gpg
          state: present
      - apt_repository:
          repo: '{{ item }}'
          state: present
          filename: mopidy
        loop:
          - deb http://apt.mopidy.com/ buster main contrib non-free
          - deb-src http://apt.mopidy.com/ buster main contrib non-free
  - name: Install required packages
    apt:
      name:
        - eject=2.1.*
        - gstreamer1.0-alsa
        - gstreamer1.0-plugins-bad
        - icecast2=2.4.*
        - ir-keytable=1.16.*
        - mopidy=3.0.*
        - mopidy-dleyna=2.0.*
        - mopidy-mpd=3.0.*
        - mpc=0.31-*
        - pulseaudio=12.2-*
        - pulseaudio-module-bluetooth
        - pulseaudio-module-raop
        - python-dev
        - python-pip
        - python-setuptools
      state: latest
      update_cache: yes
      cache_valid_time: 3600
  - name: Install additional Python modules
    pip:
      name:
        - https://github.com/vonZeppelin/inputexec/archive/13be691.zip
        - https://github.com/vonZeppelin/mopidy-cd/archive/04b9dfa.zip
        - mopidy-mobile~=1.9
        - mopidy-ydisk~=0.2
      state: latest
      executable: pip3
  - name: Configure Pulseaudio service
    block:
      - user:
          name: pulse
          groups: bluetooth
          append: yes
      - blockinfile:
          path: '/etc/pulse/{{ item.file }}'
          marker: '{{ item.marker }}'
          block: '{{ item.block }}'
        loop:
          - file: daemon.conf
            marker: '; {mark} MANAGED BLOCK'
            block: |
              allow-exit = no
              avoid-resampling = yes
              log-target = journal
              realtime-scheduling = no
              resample-method = soxr-vhq
          - file: system.pa
            marker: '# {mark} MANAGED BLOCK'
            block: |
              load-module module-bluetooth-discover
              load-module module-raop-discover
              load-module module-switch-on-connect
      - copy:
          src: conf/pulseaudio.service
          dest: /etc/systemd/system/
          owner: root
          group: root
          mode: 0644
      - systemd:
          name: pulseaudio
          enabled: yes
          state: started
          daemon_reload: yes
  - name: Configure Icecast2
    block:
      - copy:
          src: '{{ item }}'
          dest: /usr/share/icecast2/web/
          owner: icecast2
          group: icecast
          mode: 0644
        with_fileglob:
          - conf/silence.*
      - xml:
          path: /etc/icecast2/icecast.xml
          xpath: '/icecast/{{ item.key }}'
          value: '{{ item.value }}'
          pretty_print: yes
        with_dict:
          location: BMJ
          admin: bmj@bmj.org
          limits/clients: 5
          authentication/source-password: '{{ icecast_password }}'
          authentication/relay-password: '{{ icecast_password }}'
          authentication/admin-password: '{{ icecast_password }}'
          hostname: mybmj.duckdns.org
          mount/mount-name: /bmj.mp3
          mount/fallback-mount: /silence.mp3
          mount/fallback-override: 1
      - service:
          name: icecast2
          enabled: yes
          state: started
  - name: Configure Mopidy
    block:
      - user:
          name: mopidy
          groups:
            - cdrom
            - pulse-access
          append: yes
      - ini_file:
          path: /etc/mopidy/mopidy.conf
          section: '{{ item.section }}'
          option: '{{ item.option }}'
          value: '{{ item.value }}'
        loop:
          - { section: audio, option: mixer_volume, value: 20 }
          - section: audio
            option: output
            value: >-
              tee name=t !
              queue ! autoaudiosink t. !
              queue ! lamemp3enc target=quality quality=0 ! shout2send streamname=bmj description=bmj mount=bmj.mp3 password={{ icecast_password }} async=false
          - { section: file, option: enabled, value: false }
          - { section: http, option: default_app, value: mobile }
          - { section: http, option: hostname, value: 0.0.0.0 }
          - { section: mpd, option: hostname, value: 0.0.0.0 }
          - { section: stream, option: timeout, value: 15000 }
      - copy:
          src: '{{ item }}'
          dest: /var/lib/mopidy/playlists/
          owner: mopidy
          group: audio
          mode: 0644
        with_fileglob:
          - conf/playlists/*.m3u
      - service:
          name: mopidy
          enabled: yes
          state: started
  - name: Configure Remote Control
    block:
      - user:
          name: inputexec
          groups:
            - bluetooth
            - cdrom
            - input
          create_home: no
      - replace:
          path: /lib/udev/rules.d/60-ir-keytable.rules
          regexp: ^.+name"$
          replace: 'ACTION=="add", SUBSYSTEM=="input", SUBSYSTEMS=="rc", KERNEL=="event*", ENV{.rc_sysdev}="$id", RUN+="/usr/bin/ir-keytable -a /etc/rc_maps.cfg -s $env{.rc_sysdev}"'
      - lineinfile:
          path: /etc/rc_maps.cfg
          line: sunxi-ir rc-empty total_media_in_hand_02.toml
      - file:
          src: /lib/udev/rc_keymaps/total_media_in_hand_02.toml
          dest: /etc/rc_keymaps/total_media_in_hand_02.toml
          owner: root
          group: root
          state: link
      - copy:
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          owner: '{{ item.owner }}'
          group: '{{ item.group }}'
          mode: '{{ item.mode }}'
        loop:
          - { src: conf/inputexec.service, dest: /etc/systemd/system/, owner: root, group: root, mode: 644 }
          - { src: conf/inputexec.cfg, dest: /etc/inputexec/inputexec.cfg, owner: inputexec, group: input, mode: 644 }
          - { src: conf/dev_rot.py, dest: /etc/inputexec/dev_rot.py, owner: inputexec, group: input, mode: 744 }
      - copy:
          content: >
            inputexec ALL= NOPASSWD: /bin/bash
          dest: /etc/sudoers.d/inputexec
          mode: 0644
      - systemd:
          name: inputexec
          enabled: yes
          state: started
          daemon_reload: yes
  - name: Configure VirtualHere
    block:
      - get_url:
          url: https://virtualhere.com/sites/default/files/usbserver/vhusbdarm
          dest: /usr/bin/vhusbd
          owner: root
          group: root
          mode: 0744
      - copy:
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          owner: root
          group: root
        loop:
          - { src: conf/virtualhere.service, dest: /etc/systemd/system/ }
          - { src: conf/virtualhere.cfg, dest: /etc/virtualhere.cfg }
      - systemd:
          name: virtualhere
          enabled: yes
          state: started
          daemon_reload: yes
