# Tested on Armbian 5.38
# ansible-playbook -u root -k -i 192.168.0.111, playbook.yml
---
- hosts: all
  tasks:
  - name: Configure Armbian overlays
    replace:
      path: /boot/armbianEnv.txt
      regexp: ^(overlays=(?:(?!cir).)*)$
      replace: \1 cir
  - name: Install required packages
    package:
      name:
        - bluetooth
        - bluez
        - bluez-tools
        - eject
        - gstreamer1.0-alsa
        - ir-keytable
        - libdiscid0
        - mopidy
        - mopidy-dleyna
        - mpc
        - pulseaudio
        - pulseaudio-module-bluetooth
        - python-pip
      state: latest
  - name: Install additional Python modules
    pip:
      name:
        - inputexec
        - git+https://github.com/vonZeppelin/bmj#egg=mopidy-cd&subdirectory=mopidy-cd
      state: latest
  - name: Configure Pulseaudio service
    block:
      - user:
          name: pulse
          groups: bluetooth
          append: yes
      - lineinfile:
          path: /etc/pulse/system.pa
          line: 'load-module {{ item }}'
        loop:
          - module-bluetooth-discover
          - module-bluetooth-policy
          - module-switch-on-connect
      - copy:
          src: pulseaudio.service
          dest: /etc/systemd/system/
          owner: root
          group: root
          mode: 0644
      - systemd:
          name: pulseaudio
          enabled: yes
          state: started
          daemon_reload: yes
  - name: Configure Mopidy
    block:
      - user:
          name: mopidy
          groups:
            - cdrom
            - pulse-access
          append: yes
      - ini_file:
          path: /etc/mopidy/mopidy.conf
          section: '{{ item.section }}'
          option: '{{ item.option }}'
          value: '{{ item.value }}'
        loop:
          - { section: file, option: enabled, value: false }
          - { section: http, option: enabled, value: false }
          - { section: local, option: enabled, value: false }
          - { section: mpd, option: hostname, value: 0.0.0.0 }
      - copy:
          src: online-radio.m3u
          dest: /var/lib/mopidy/playlists
          owner: mopidy
          group: audio
          mode: 0644
      - service:
          name: mopidy
          enabled: yes
          state: started
  - name: Configure Remote Control
    block:
      - user:
          name: inputexec
          groups:
            - cdrom
            - input
          create_home: no
      - replace:
          path: '{{ item.path }}'
          regexp: '{{ item.regexp }}'
          replace: '{{ item.replace }}'
        loop:
          - {
            path: /lib/udev/rules.d/60-ir-keytable.rules,
            replace: 'ACTION=="add", SUBSYSTEM=="input", SUBSYSTEMS=="rc", KERNEL=="event*", ENV{.rc_sysdev}="$id", RUN+="/usr/bin/ir-keytable -a /etc/rc_maps.cfg -s $env{.rc_sysdev}"',
            regexp: ^.+name"$
          }
          - {
            path: /etc/rc_maps.cfg,
            replace: '* rc-empty tmih',
            regexp: ^.+total_media_in_hand$
          }
      - copy:
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          owner: '{{ item.owner }}'
          group: '{{ item.group }}'
          mode: 0644
        loop:
          - { src: inputexec.service, dest: /etc/systemd/system/, owner: root, group: root }
          - { src: inputexec.cfg, dest: /etc/inputexec.cfg, owner: inputexec, group: input }
          - { src: tmih, dest: /etc/rc_keymaps/, owner: root, group: root }
      - lineinfile:
          path: /etc/sudoers.d/inputexec
          line: 'inputexec ALL= NOPASSWD: /bin/bash,/sbin/poweroff'
          create: yes
          mode: 0644
      - systemd:
          name: inputexec
          enabled: yes
          state: started
          daemon_reload: yes
